server:
  port: 9010
spring:
  datasource:
    url: jdbc:mysql://DB_HOST:DB_PORT/DB_NAME?useSSL=false&characterEncoding=UTF-8&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: DB_USER
    password: DB_PASSWORD
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    lazy-initialization: true

agile:
  spring:
    upload:
      aliyun-oss:
        access-key-id: 阿里云 OSS accessKeyId
        access-key-secret: 阿里云 OSS accessKeySecret
        endpoint: 阿里云 OSS 数据中心访问域名
        bucket: 阿里云 OSS Bucket
        directory: 阿里云文件目录
      tencent-cos:
        app-id: 腾讯云 COS appId
        secret-id: 腾讯云 COS secretId
        secret-key: 腾讯云 COS secretKey
        bucket: 腾讯云 COS 存储桶空间名称
        region: 腾讯云 COS 所属区域
        directory: 腾讯云文件目录