server:
  port: 9010
spring:
  datasource:
    url: jdbc:mysql://DB_HOST:DB_PORT/DB_NAME?useSSL=false&characterEncoding=UTF-8&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: DB_USER
    password: DB_PASSWORD
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    lazy-initialization: true