server:
  compression:
    enabled: true
spring:
  application:
    name: agile-boot-admin-api
  profiles:
    active: dev
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    web:
      pageable:
        default-page-size: 20
        size-parameter: size
        page-parameter: page
        one-indexed-parameters: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 50
    open-in-view: false
  datasource:
    hikari:
      max-lifetime: 120000
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jmx:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Shanghai
