server:
  compression:
    enabled: true
spring:
  application:
    name: agile-boot-admin-api
  profiles:
    active: dev
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    hikari:
      max-lifetime: 28800
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jmx:
    enabled: false
