server:
  port: 9010
spring:
  datasource:
    url: jdbc:mysql://DB_HOST:DB_PORT/DB_NAME?useSSL=false&characterEncoding=UTF-8&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true&useLegacyDatetimeCode=false
    username: DB_USER
    password: DB_PASSWORD
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      generate_statistics: false
      show-sql: true
  main:
    lazy-initialization: true

agile:
  spring:
    upload:
      aliyun-oss:
        access-key-id: 阿里云 OSS accessKeyId
        access-key-secret: 阿里云 OSS accessKeySecret
        endpoint: 阿里云 OSS 数据中心访问域名
        bucket: 阿里云 OSS Bucket
        directory: 阿里云文件目录
      tencent-cos:
        app-id: 腾讯云 COS appId
        secret-id: 腾讯云 COS secretId
        secret-key: 腾讯云 COS secretKey
        bucket: 腾讯云 COS 存储桶空间名称
        region: 腾讯云 COS 所属区域
        directory: 腾讯云文件目录
        ci-host: 数据万象图片处理域名
        ci-delimiter: 图片样式分割符号，默认 / 斜杠
      local-file:
        access-path: 上传文件访问路径 # 比如 /files/**
        upload-path: 上传目录 # 使用 file: 开头表示相对系统的绝对路径，否则使用 jar 包所在目录的相对路径
        corp-action: /open/crop-image # 图片切割 action
        upload-action: /open/upload-file # 图片上传 action
        policy-key: 自定义密钥 # 必须是16位长度

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE